# Generated by Django 2.2.6 on 2019-10-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Администратор'), ('2', 'Пользователь')], default=2, max_length=100, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Название')),
                ('memory', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Память')),
                ('os', models.CharField(blank=True, max_length=255, null=True, verbose_name='Операционная система')),
                ('id_naumen', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер в Naumen')),
                ('id_invent', models.PositiveIntegerField(blank=True, null=True, verbose_name='Инвентарный номер')),
                ('id_sn', models.PositiveIntegerField(blank=True, null=True, verbose_name='Серийный номер')),
                ('arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ARM', verbose_name='АРМ')),
            ],
            options={
                'verbose_name': 'Системный блок',
                'verbose_name_plural': 'Системные блоки',
            },
        ),
    ]
