# Generated by Django 2.2.6 on 2019-10-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191028_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Изспользуется'),
        ),
        migrations.AddField(
            model_name='unit',
            name='retired',
            field=models.BooleanField(default=False, verbose_name='На списании'),
        ),
    ]
