# Generated by Django 2.2.6 on 2019-10-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191029_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Используется'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id_invent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id_naumen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер в Naumen'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id_sn',
            field=models.CharField(default='', max_length=255, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='retired',
            field=models.BooleanField(default=False, verbose_name='Списан'),
        ),
    ]
