# Generated by Django 2.2.6 on 2019-11-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191030_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='active',
        ),
    ]
